#Decision Trees

- In the decision tree, if all the occurrances is true or green, the there is a low entropy.
- If the occurances is 50% on each side then the entropy is one.
- Entropy is the measure of the randomness.

Importing Libraries

In [25]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.preprocessing import LabelEncoder

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
df = pd.read_csv('/content/drive/MyDrive/salaries.csv')
df

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

Seperating the variables

In [14]:
features = df.drop('salary_more_then_100k', axis='columns')
target = df['salary_more_then_100k']

In [15]:
features

       company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [16]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

Crearing new columns with integers instread of strigns

In [17]:
Le_company = LabelEncoder()
Le_job = LabelEncoder()
Le_degree = LabelEncoder()

In [20]:
features['company_n'] = Le_company.fit_transform(features['company'])
features['job_n'] = Le_job.fit_transform(features['job'])
features['degree_n'] = Le_degree.fit_transform(features['degree'])
features.head()

  company                  job     degree  company_n  job_n  degree_n
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

Droping previous columns with values in the form of strings

In [24]:
features_n = features.drop(['company', 'job', 'degree'], axis='columns')
features_n.head()

   company_n  job_n  degree_n
0          2      2         0
1          2      2         1
2          2      0         0
3          2      0         1
4          2      1         0

Training the model

In [27]:
model_dt = tree.DecisionTreeClassifier()

In [28]:
model_dt.fit(features_n, target)

DecisionTreeClassifier()

In [29]:
model_dt.score(features_n, target)

1.0

The score is 1 because we use the same dataset for training and testing purpose.

Make Predictions

In [30]:
model_dt.predict([[2, 0, 1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])