#Linear Regression Multivariable

Importing Libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

Mount Google Drive

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

Reading CSV File

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/hiring.csv')
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

This candidates data has one missing value in test_score column.
Fill the missing value by finding the median of each value in this column.

In [ ]:
import math
median_testscore = math.floor(df['test_score(out of 10)'].median())
median_testscore

8

In [ ]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_testscore)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

Now we need to convert 'experience' column from strings to float.

- First fill empty values with zeros.

In [ ]:
df.experience = df.experience.fillna("zero")
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

Assign strings to its corrosponding values

In [ ]:
def word_to_num(word):
    word_map = {
        'zero': 0,
        'two': 2,
        'three': 3,
        'five': 5,
        'seven': 7,
        'ten': 10,
        'eleven': 11,
    }
    return word_map.get(word, word)

Now, convert strings to float.

In [ ]:
df.experience = df.experience.apply(word_to_num)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

Seperating the variables

In [ ]:
model_lr = linear_model.LinearRegression()

In [ ]:
model_lr.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

###Make Pridictions

> 2 year experience, 9 test scores and 6 interviews

In [ ]:
model_lr.predict([[2, 9, 6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53205.96797671])

- The above is giving predictions of 53205 salary based on the givenn input.
-  However, when we increase the experince and an interview then the salary would be increased as in the next predictions below

> 12 year experience, 10 test scores and 10 interviews

In [ ]:
model_lr.predict([[12, 10, 10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([92002.18340611])