#Naive Bayes Classifier

In [53]:
import seaborn as sns #!
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

df_titanic = sns.load_dataset(name='titanic')
df_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [36]:
df_titanic = sns.load_dataset(name='titanic')[['pclass', 'sex', 'age', 'fare', 'survived']]
df_titanic.head()

   pclass     sex   age     fare  survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [37]:
df_titanic.describe()

           pclass         age        fare    survived
count  891.000000  714.000000  891.000000  891.000000
mean     2.308642   29.699118   32.204208    0.383838
std      0.836071   14.526497   49.693429    0.486592
min      1.000000    0.420000    0.000000    0.000000
25%      2.000000   20.125000    7.910400    0.000000
50%      3.000000   28.000000   14.454200    0.000000
75%      3.000000   38.000000   31.000000    1.000000
max      3.000000   80.000000  512.329200    1.000000

In [38]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    object
 2   age       714 non-null    float64
 3   fare      891 non-null    float64
 4   survived  891 non-null    int64
dtypes: float64(2), int64(2), object(1)
memory usage: 34.9+ KB

In [39]:
target = df_titanic['survived']
inputs = df_titanic.drop(columns='survived')

In [40]:
df_titanic = pd.get_dummies(inputs.sex)
df_titanic.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [41]:
inputs = pd.concat([inputs, df_titanic], axis='columns')
inputs.head()

   pclass     sex   age     fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [42]:
inputs.drop('sex', axis='columns', inplace=True)
inputs.head()

   pclass   age     fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [44]:
inputs.columns[inputs.isna().any()]

Index(['age'], dtype='object')

In [45]:
inputs['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [61]:
inputs.age = inputs.age.fillna(inputs.age.mean())
inputs

     pclass        age     fare  female  male
0         3  22.000000   7.2500       0     1
1         1  38.000000  71.2833       1     0
2         3  26.000000   7.9250       1     0
3         1  35.000000  53.1000       1     0
4         3  35.000000   8.0500       0     1
..      ...        ...      ...     ...   ...
886       2  27.000000  13.0000       0     1
887       1  19.000000  30.0000       1     0
888       3  29.699118  23.4500       1     0
889       1  26.000000  30.0000       0     1
890       3  32.000000   7.7500       0     1

[891 rows x 5 columns]

In [62]:
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)

In [63]:
model_nb = GaussianNB()

In [64]:
model_nb.fit(X_train, y_train)

GaussianNB()

In [65]:
model_nb.score(X_test, y_test)

0.8268156424581006

In [68]:
X_test[:10]

     pclass        age      fare  female  male
557       1  29.699118  227.5250       0     1
659       1  58.000000  113.2750       0     1
104       3  37.000000    7.9250       0     1
554       3  22.000000    7.7750       1     0
152       3  55.500000    8.0500       0     1
90        3  29.000000    8.0500       0     1
559       3  36.000000   17.4000       1     0
567       3  29.000000   21.0750       1     0
770       3  24.000000    9.5000       0     1
609       1  40.000000  153.4625       1     0

In [70]:
y_test[:10]

557    0
659    0
104    0
554    1
152    0
90     0
559    1
567    0
770    0
609    1
Name: survived, dtype: int64

In [75]:
model_nb.predict(X_test[:10])

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 1])

In [76]:
model_nb.predict_proba(X_test[:10])

array([[3.83619554e-07, 9.99999616e-01],
       [1.80304984e-01, 8.19695016e-01],
       [9.87588599e-01, 1.24114012e-02],
       [5.20530562e-02, 9.47946944e-01],
       [9.85428547e-01, 1.45714533e-02],
       [9.87010359e-01, 1.29896411e-02],
       [6.04644420e-02, 9.39535558e-01],
       [5.72770560e-02, 9.42722944e-01],
       [9.86234740e-01, 1.37652598e-02],
       [5.93449266e-06, 9.99994066e-01]])